### ISSUE TITLE
Love the code, but it does not export last page

### ISSUE THREAD

**Issue by dpt-78** [santhoshkanala/azureretailpricesapi#1]
Hi,

Thanks for this code, it works great however it does not get/export the last page of the API call.  Please can you help me and expalin how i can get/export the last page of results.

Thanks

David

**Comment by santhoshkanala** [comment]
I'll take a look at the script and get back to you. Thanks for reporting the issue.

**Comment by santhoshkanala** [comment]
@dpt-78 Fixed the reported issue. Now the script retrieves the results of the last page as well. Please get the latest code.
Thanks again for reporting the issue. Please close the issue once you verify at your end.

FYI - Added an update section to the readme file. 

Microsoft made changes recently to list prices in different currencies. Added couple of examples in the readme section on how to do it.

**Comment by dpt-78** [comment]
Thanks, that works perfectly now...Appreciate it..
